package com.tanzeelkazi.core;

import java.util.Map;
import java.util.TreeMap;

public class Error {
    
    public static enum Type {
        
        // core
        
        NONE(-1),
        SUCCESS(0),
        FAIL(1),
        NOT_IMPLEMENTED(2),
        
        // core validator errors
        NULL_OR_EMPTY(101),
        NOT_NULL_OR_EMPTY(102),
        
        INVALID_EMAIL(103),
        VALID_EMAIL(104)
        
        // core.mail
        
        ;
        
        private static Map<Integer, Type> valueMap = new TreeMap<Integer,Type>();
        //private static final int START_VALUE = -1;
        private int value;
        
        static {
            for(int i=0;i<values().length;i++)
            {
                valueMap.put(values()[i].value, values()[i]);
            }
        }
        
        public static Type fromInt(int i) {
            return valueMap.get(i);
        }
        
        private Type(int value) {
            this.value = value;
        }
        
        public int value() {
            return this.value;
        }
    }
    
    private Type _errorType;
    private int _errorCode;
    private Exception _exception = null;
    
    public Error() {
        this.setErrorType(Type.NONE);
        return;
    }
    
    public Error(Type errorType) {
        this.setErrorType(errorType);
        return;
    }
    
    public Error(int errorCode) {
        this.setErrorCode(errorCode);
        return;
    }
    
    
    public void setErrorType(Type errorType) {
        this._errorType = errorType;
        this._errorCode = this._errorType.value();
        return;
    }
    
    public Type getErrorType() {
        return this._errorType;
    }
    
    
    public void setErrorCode(int errorCode) {
        this._errorType = Type.fromInt(errorCode);
        this._errorCode = errorCode;
        return;
    }
    
    public int getErrorCode() {
        return this._errorCode;
    }
    
    
    public void setException(Exception ex) {
        this._exception = ex;
        return;
    }
    
    public Exception getException() {
        return this._exception;
    }
}
